data = [
    {
        "firstName": "John",
        "lastName": "Doe",
        "mobileNumber": 9876543211,
        "countryCode": "+91",
        "age": 30,
        "skills": ["Coding", "Debugging", "Testing"],
        "address": {
            "street": "MG Road",
            "city": "Bangalore",
            "state": "Karnataka",
            "country": "India",
        },
    },
    {
        "firstName": "Jane",
        "lastName": "Smith",
        "mobileNumber": 9876543212,
        "countryCode": "+91",
        "age": 25,
        "skills": ["Designing", "Drawing", "Illustrating"],
        "address": {
            "street": "Park Street",
            "city": "Kolkata",
            "state": "West Bengal",
            "country": "India",
        },
    },
    {
        "firstName": "Alice",
        "lastName": "Johnson",
        "mobileNumber": 9876543213,
        "countryCode": "+91",
        "age": 28,
        "skills": ["Project Management", "Scrum", "Agile"],
        "address": {
            "street": "LBS Marg",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
        },
    },
    {
        "firstName": "Bob",
        "lastName": "Brown",
        "mobileNumber": 9876543214,
        "countryCode": "+91",
        "age": 35,
        "skills": ["Networking", "Security", "Firewall"],
        "address": {
            "street": "Anna Salai",
            "city": "Chennai",
            "state": "Tamil Nadu",
            "country": "India",
        },
    },
    {
        "firstName": "Charlie",
        "lastName": "Davis",
        "mobileNumber": 9876543215,
        "countryCode": "+91",
        "age": 40,
        "skills": ["Marketing", "Sales", "Communication"],
        "address": {
            "street": "Brigade Road",
            "city": "Bangalore",
            "state": "Karnataka",
            "country": "India",
        },
    },
    {
        "firstName": "David",
        "lastName": "Evans",
        "mobileNumber": 9876543216,
        "countryCode": "+91",
        "age": 27,
        "skills": ["Data Analysis", "SQL", "Python"],
        "address": {
            "street": "Sarjapur Road",
            "city": "Bangalore",
            "state": "Karnataka",
            "country": "India",
        },
    },
    {
        "firstName": "Eve",
        "lastName": "Foster",
        "mobileNumber": 9876543217,
        "countryCode": "+91",
        "age": 32,
        "skills": ["Writing", "Editing", "Proofreading"],
        "address": {
            "street": "Connaught Place",
            "city": "Delhi",
            "state": "Delhi",
            "country": "India",
        },
    },
    {
        "firstName": "Frank",
        "lastName": "Green",
        "mobileNumber": 9876543218,
        "countryCode": "+91",
        "age": 45,
        "skills": ["Teaching", "Mentoring", "Research"],
        "address": {
            "street": "Marine Drive",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
        },
    },
    {
        "firstName": "Grace",
        "lastName": "Harris",
        "mobileNumber": 9876543219,
        "countryCode": "+91",
        "age": 29,
        "skills": ["Public Speaking", "Leadership", "Management"],
        "address": {
            "street": "MG Road",
            "city": "Pune",
            "state": "Maharashtra",
            "country": "India",
        },
    },
    {
        "firstName": "Hank",
        "lastName": "Iyer",
        "mobileNumber": 9876543220,
        "countryCode": "+91",
        "age": 38,
        "skills": ["Engineering", "Design", "Problem Solving"],
        "address": {
            "street": "Outer Ring Road",
            "city": "Hyderabad",
            "state": "Telangana",
            "country": "India",
        },
    },
]
